---
jobs:
- name: publish
  public: true
  serial: true
  plan:
  - get: source
    trigger: true
  - put: image
    params:
      build: source
  - put: deliver-story
    params:
      path: source
      comment: Delivered to Docker Hub by Concourse after successful pipeline run


resources:
- name: source
  type: git
  source:
    uri: ((git-server-base))/((git-username))/((image-name))
    branch: ((git-branch))

- name: image
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/((image-name))

- name: deliver-story
  type: tracker
  source:
    token: ((tracker-api-token))
    project_id: ((tracker-project-id))
    tracker_url: ((tracker-url))
